name: CI my first pipeline

on:
  push:
    branches: ["main"]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo 'Hello world'
      - name: Display Node.js version
        run: node --version
      - name: Display npm version
        run: npm --version
      - name: Print Working Directory
        run: pwd
      - name: List Files
        run: ls

    
