name: CI my first pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Install Client Depen
        working-directory: client
        run: npm ci

      - name: Install server Depen
        working-directory: server
        run: npm ci

      - name: Lint Frontend
        working-directory: client
        run: npm run lint

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Test Backend
        working-directory: server
        env: 
          MONGO_URI: ${{secrets.MONGO_URI}}
        run: npm test


  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install client Dep
          working-directory: client
          run: npm ci

        - name: Build frontend
          working-directory: client
          run: npm run build

        
